language: python
python:
  - "3.10"

services:
  - docker

git:
  depth: 2

branches:
  only:
    - master
    - tests

jobs:
  include:
    - stage: test
      script:
      - docker-compose up --build -d
      - cd tests
      - pytest tests.py

after_success:
  - docker-compose down

notifications:
  email:
    recipients:
      - armandobp765@gmail.com
    on_success: always
    on_failure: always
