language: python

services:
  - docker

git:
  depth: 2

branches:
  only:
    - master
    - tests

jobs:
  include:
    - stage: test
      script:
      - docker-compose
      - cd tests
      - pytest tests.py

notifications:
  email:
    recipients:
      - armandobp765@gmail.com
    on_success: always
    on_failure: always
