version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: compose/app/DOCKERFILE
    depends_on:
      - db
    restart: always
    volumes:
      - .:/app/
    env_file: compose/app/example.env

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./compose/db:/docker-entrypoint-initdb.d/
    env_file:
      - ./compose/db/example.env
    restart: always